-- MySQL Script generated by MySQL Workbench
-- Sun Jan 10 16:07:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema citas_medicas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `citas_medicas` ;

-- -----------------------------------------------------
-- Schema citas_medicas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citas_medicas` DEFAULT CHARACTER SET utf8 ;
USE `citas_medicas` ;

-- -----------------------------------------------------
-- Table `citas_medicas`.`FacturaCabecera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`FacturaCabecera` (
  `idFacturaCabecera` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `subTotal` FLOAT NOT NULL,
  `iva` FLOAT NULL,
  `total` FLOAT NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idFacturaCabecera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NULL,
  `FacturaCabecera_idFacturaCabecera` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  INDEX `fk_Paciente_FacturaCabecera1_idx` (`FacturaCabecera_idFacturaCabecera` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_FacturaCabecera1`
    FOREIGN KEY (`FacturaCabecera_idFacturaCabecera`)
    REFERENCES `citas_medicas`.`FacturaCabecera` (`idFacturaCabecera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Horario` (
  `idHorario` INT NOT NULL,
  `horaIngreso` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Medico` (
  `idMedico` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `Horario_idHorario`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  INDEX `fk_Medico_Horario1_idx` (`Horario_idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `citas_medicas`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Especialidad` (
  `idEspecialidad` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Medico_Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idEspecialidad`),
  INDEX `fk_Especialidad_Medico1_idx` (`Medico_idMedico` ASC, `Medico_Horario_idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidad_Medico1`
    FOREIGN KEY (`Medico_idMedico` , `Medico_Horario_idHorario`)
    REFERENCES `citas_medicas`.`Medico` (`idMedico` , `Horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Secretaria` (
  `idSecretaria` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSecretaria`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`CitaMedica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`CitaMedica` (
  `idCitaMedica` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `Secretaria_idSecretaria` INT NOT NULL,
  PRIMARY KEY (`idCitaMedica`),
  INDEX `fk_CitaMedica_Secretaria1_idx` (`Secretaria_idSecretaria` ASC) VISIBLE,
  CONSTRAINT `fk_CitaMedica_Secretaria1`
    FOREIGN KEY (`Secretaria_idSecretaria`)
    REFERENCES `citas_medicas`.`Secretaria` (`idSecretaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`FacturaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`FacturaDetalle` (
  `idFacturaDetalle` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `FacturaCabecera_idFacturaCabecera` INT NOT NULL,
  PRIMARY KEY (`idFacturaDetalle`),
  INDEX `fk_FacturaDetalle_FacturaCabecera_idx` (`FacturaCabecera_idFacturaCabecera` ASC) VISIBLE,
  CONSTRAINT `fk_FacturaDetalle_FacturaCabecera`
    FOREIGN KEY (`FacturaCabecera_idFacturaCabecera`)
    REFERENCES `citas_medicas`.`FacturaCabecera` (`idFacturaCabecera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`ExamenesMedicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`ExamenesMedicos` (
  `idExamenesMedicos` INT NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `fecha` DATE NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Medico_Horario_idHorario` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idExamenesMedicos`, `Paciente_idPaciente`),
  INDEX `fk_ExamenesMedicos_Medico1_idx` (`Medico_idMedico` ASC, `Medico_Horario_idHorario` ASC) VISIBLE,
  INDEX `fk_ExamenesMedicos_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_ExamenesMedicos_Medico1`
    FOREIGN KEY (`Medico_idMedico` , `Medico_Horario_idHorario`)
    REFERENCES `citas_medicas`.`Medico` (`idMedico` , `Horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExamenesMedicos_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `citas_medicas`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`PrescripcionMedica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`PrescripcionMedica` (
  `idPrescripcionMedica` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Medico_Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idPrescripcionMedica`),
  INDEX `fk_PrescripcionMedica_Medico1_idx` (`Medico_idMedico` ASC, `Medico_Horario_idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_PrescripcionMedica_Medico1`
    FOREIGN KEY (`Medico_idMedico` , `Medico_Horario_idHorario`)
    REFERENCES `citas_medicas`.`Medico` (`idMedico` , `Horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`HistoriaClinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`HistoriaClinica` (
  `idHistoriaClinica` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `CitaMedica_idCitaMedica` INT NOT NULL,
  PRIMARY KEY (`idHistoriaClinica`, `Paciente_idPaciente`),
  INDEX `fk_HistoriaClinica_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_HistoriaClinica_CitaMedica1_idx` (`CitaMedica_idCitaMedica` ASC) VISIBLE,
  CONSTRAINT `fk_HistoriaClinica_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `citas_medicas`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistoriaClinica_CitaMedica1`
    FOREIGN KEY (`CitaMedica_idCitaMedica`)
    REFERENCES `citas_medicas`.`CitaMedica` (`idCitaMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas_medicas`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas_medicas`.`Medicamento` (
  `idMedicamento` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `HistoriaClinica_idHistoriaClinica` INT NOT NULL,
  `HistoriaClinica_Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idMedicamento`, `HistoriaClinica_idHistoriaClinica`, `HistoriaClinica_Paciente_idPaciente`),
  INDEX `fk_Medicamento_HistoriaClinica1_idx` (`HistoriaClinica_idHistoriaClinica` ASC, `HistoriaClinica_Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamento_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_idHistoriaClinica` , `HistoriaClinica_Paciente_idPaciente`)
    REFERENCES `citas_medicas`.`HistoriaClinica` (`idHistoriaClinica` , `Paciente_idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
